name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *
    - cron: 30 05 * * 1-5

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

      - name: Install Newman and html extra
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with Newman
        run: |
             newman run 'In-warranty flow collection Copy 2.postman_collection.json' \
             -e 'QA.postman_environment.json' \
             -d 'testdata.csv' \
             -r cli,htmlextra

      
      
