name : Postman Collection Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 30 02 * * *
    - cron: 00 14 * * *
    - cron: 30 05 * * 1-5

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v6.0.2

      - name: Install Node.js and NPM
        uses: actions/setup-node@v6.2.0
        with:
          node-version: '22'

      - name: Install Newman and html extra
        run: |
             npm install -g newman
             npm install -g newman-reporter-htmlextra

      - name: Run the Postman collection with Newman
        run: |
             newman run 'In-warranty flow collection Copy 2.postman_collection.json' \
             -e 'QA.postman_environment.json' \
             -d 'testdata.csv' \
             -r cli,htmlextra \
             --reporter-htmlextra-export ./newman/index.html

      - name: Newman Report
        if: always()
        uses: actions/upload-artifact@v6.0.0
        with:
          name: Newman Report
          path: newman/*.html
      - name: Create GitHub page branch
        if: always()
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: newman/
      - name: Send Email Notification
        if: always()
        uses: dawidd6/action-send-mail@v8
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Phoenix InWarranty Flow Test Execution Notification
          to: shivajisjbbajpai@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
                  Hi,
                  Phoenix Inwarranty Flow Test flow has been executed. The report has been published and the URL
                  is https://shivajibajpai.github.io/Phoenix-InWarranty-Flow/
            
      
      
